// swift-tools-version:5.7
// This file is generated by scripts/spm/generate-remote-package-swift.sh (CI).
// Do not edit by hand — rerun the SPM release workflow instead.
import PackageDescription

let release = "v9.0.0"

let frameworks: [String: String] = [
    "libavcodec": "825b89e4c2bda599f2b9bebc43775e3ce5c737f75d9061048a3488299a06d2d7",
    "libavdevice": "f7a387e0f3e810016a3338cec5c7be0788954824024fb0c51ab5251f850573f8",
    "libavfilter": "af3f536e07be02084a1d8f5fc95a84bbd6ded2d2cddb1ff42d680f1826d8575d",
    "libavformat": "b1ea888220e4be4d82e7e0045093c1e106a16a9a33a78871c72f6a31135fdcdf",
    "libavutil": "34fca3a0ad9760482f5976d655c821f9038b568e79e100743dd4871119b5523c",
    "libswresample": "7f76bcf9178bd64f64f3df6d5182cb95f556b9b41e09078ac4321671d0942270",
    "libswscale": "07b9105e20d7acb9ca48c9abcfc1532ccc42ddd9ed25e13febbdb0ad287b00a7",
    "ffmpegkit": "3ccc23c0acba6f6229e5098aeab94ce1c9699c98171e2c38cd86780c42720c05",
]

func xcframework(_ entry: Dictionary<String, String>.Element) -> Target {
    let url = "https://github.com/AwesomeTy18/ffmpeg-kit-next/releases/download/\(release)/\(entry.key).xcframework.zip"
    return .binaryTarget(name: entry.key, url: url, checksum: entry.value)
}

let package = Package(
    name: "ffmpeg-kit",
    platforms: [
        .iOS("12.1"),
        .macOS("10.15")
    ],
    products: [
        .library(
            name: "ffmpeg-kit",
            targets: frameworks.keys.sorted().map { $0 }
        )
    ],
    targets: frameworks.map { xcframework($0) }
)
