#!/usr/bin/env bash
# Generate a root Package.swift that uses remote binaryTarget URLs + checksums.
# Usage:
#   generate-remote-package-swift.sh <prebuilt-dir> <github-owner/repo> <tag> <out-file>
set -euo pipefail

PREBUILT_DIR="${1:?prebuilt dir}"
REPO="${2:?owner/repo}"
TAG="${3:?tag}"
OUT_FILE="${4:?output Package.swift path}"

LIBS=(libavcodec libavdevice libavfilter libavformat libavutil libswresample libswscale ffmpegkit)

if [[ ! -d "${PREBUILT_DIR}" ]]; then
  echo "error: prebuilt dir not found: ${PREBUILT_DIR}" >&2
  exit 1
fi

declare -A CHECKSUMS=()
for LIB in "${LIBS[@]}"; do
  XCF="${PREBUILT_DIR}/${LIB}.xcframework"
  ZIP="${PREBUILT_DIR}/${LIB}.xcframework.zip"
  if [[ ! -d "${XCF}" ]]; then
    echo "error: missing ${XCF}" >&2
    exit 1
  fi
  rm -f "${ZIP}"
  # Zip the xcframework directory itself (SPM expects the zip to expand to Name.xcframework/)
  (
    cd "${PREBUILT_DIR}"
    ditto -c -k --sequesterRsrc --keepParent "${LIB}.xcframework" "${LIB}.xcframework.zip"
  )
  CHECKSUMS["${LIB}"]="$(swift package compute-checksum "${ZIP}")"
  echo "checksum ${LIB}=${CHECKSUMS[${LIB}]}"
done

{
  cat <<'HEADER'
// swift-tools-version:5.7
// This file is generated by scripts/spm/generate-remote-package-swift.sh (CI).
// Do not edit by hand — rerun the SPM release workflow instead.
import PackageDescription

HEADER
  echo "let release = \"${TAG}\""
  echo ""
  echo "let frameworks: [String: String] = ["
  for LIB in "${LIBS[@]}"; do
    echo "    \"${LIB}\": \"${CHECKSUMS[${LIB}]}\","
  done
  cat <<'BODY'
]

func xcframework(_ entry: Dictionary<String, String>.Element) -> Target {
    let url = "https://github.com/REPO_PLACEHOLDER/releases/download/\(release)/\(entry.key).xcframework.zip"
    return .binaryTarget(name: entry.key, url: url, checksum: entry.value)
}

let package = Package(
    name: "ffmpeg-kit",
    platforms: [
        .iOS("12.1"),
        .macOS("10.15")
    ],
    products: [
        .library(
            name: "ffmpeg-kit",
            targets: frameworks.keys.sorted().map { $0 }
        )
    ],
    targets: frameworks.map { xcframework($0) }
)
BODY
} > "${OUT_FILE}.tmp"

# Inject owner/repo into the URL template
sed "s|REPO_PLACEHOLDER|${REPO}|g" "${OUT_FILE}.tmp" > "${OUT_FILE}"
rm -f "${OUT_FILE}.tmp"

echo "Wrote ${OUT_FILE}"
